version: '3.9'
services:
  # docker compose up -d server
  server:
    image: nginx
    working_dir: /var/www/html
    ports:
      - "${APP_PORT:-80}:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf.tamplate:/etc/nginx/conf.d/nginx.conf.tamplate
    command: /bin/sh /var/www/html/docker/nginx/nginx_start.sh
    depends_on:
      - php_fpm
      - db
      - pma
      - interface
  php_fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php.dockerfile
    image: user_country_php_fpm
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - .:/var/www/html
  interface:
    image: node:18
    working_dir: /var/www/html
    env_file:
      - .env
    command: npm run watch
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql:8
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_FORWORD_PORT:-3306}:3306" 
  pma:
    image: phpmyadmin:5.2.1
    ports:
      - "${PMA_FORWORD_PORT:-8080}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
  ############## Utility containers ##############
  # docker compose run --rm composer ...
  composer:
    image: composer:2.5.8
    working_dir: /var/www/html
    env_file:
      - .env
    entrypoint: composer
    volumes:
      - .:/var/www/html
  # docker compose run --rm artisan ...
  artisan:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php.dockerfile
    image: user_country_php_fpm
    working_dir: /var/www/html
    env_file:
      - .env
    entrypoint: php artisan
    volumes:
      - .:/var/www/html
  # docker compose run --rm npm ...
  npm:
    image: node:16
    working_dir: /var/www/html
    env_file:
      - .env
    entrypoint: npm
    volumes:
      - .:/var/www/html
volumes:
  mysql_data: